# Generated by Django 4.0.1 on 2022-02-26 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_remove_quotation_addon_type_remove_quotation_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_width', models.FloatField(verbose_name='Frame Width')),
                ('frame_height', models.FloatField(verbose_name='Frame Height')),
                ('frame_rate', models.FloatField(verbose_name='Frame Rate')),
                ('glass_rate', models.FloatField(verbose_name='Glass Rate')),
                ('il_rate', models.FloatField(verbose_name='I/L patti Rate')),
                ('net_rate', models.FloatField(verbose_name='Net Rate')),
                ('uch_rate', models.FloatField(verbose_name='U-channel Rate')),
                ('coat_rate', models.FloatField(verbose_name='Coating Rate')),
                ('qty', models.PositiveIntegerField(verbose_name='Quantity')),
                ('coat_type', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.PROTECT, to='app.coat', verbose_name='Coating Type')),
                ('frame_bar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.length', verbose_name='Frame Unit size')),
                ('frame_type', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.PROTECT, to='app.frame')),
                ('glass_type', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.PROTECT, to='app.glass', verbose_name='Glass Type')),
                ('il_type', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.PROTECT, to='app.ilpatti', verbose_name='I/L patti Type')),
                ('net_type', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.PROTECT, to='app.mnet', verbose_name='Net Type')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.product')),
                ('uch_type', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.PROTECT, to='app.uchannel', verbose_name='U-channel Type')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField(auto_created=True, verbose_name='Quotation Id')),
                ('addon_rate', models.FloatField(verbose_name='Addon Rate')),
                ('addon_type', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.PROTECT, to='app.addon', verbose_name='Addon Type')),
                ('items', models.ManyToManyField(to='qoute.Products', verbose_name='items')),
            ],
        ),
    ]
