# Generated by Django 4.0.1 on 2022-05-05 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, verbose_name='Item Name')),
                ('rate', models.FloatField(verbose_name='Rate')),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Clip Name')),
            ],
        ),
        migrations.CreateModel(
            name='Coat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Coating Name')),
                ('rate', models.FloatField(verbose_name='Rate')),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Frame Name')),
            ],
        ),
        migrations.CreateModel(
            name='Glass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Glass Name')),
            ],
        ),
        migrations.CreateModel(
            name='Ilpatti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='I/l Patti Name')),
            ],
        ),
        migrations.CreateModel(
            name='Length',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Length')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Mnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Mosquito Net Name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Product Code')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('discription', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('total_qty', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Total Qty')),
                ('totalvalue', models.FloatField(verbose_name='Total Value')),
                ('totalsize', models.FloatField(verbose_name='Total Size')),
                ('totallabour', models.FloatField(verbose_name='Total labour')),
                ('total_transport_charge', models.FloatField(verbose_name='Total Transport Charge')),
                ('finalvalue', models.FloatField(verbose_name='Final Value')),
                ('gst', models.FloatField(verbose_name='GST')),
                ('summery', models.FloatField(verbose_name='Grand Total')),
                ('quotation_date', models.DateField()),
                ('to', models.CharField(max_length=50, verbose_name='To')),
                ('to_address_line_1', models.CharField(max_length=20, verbose_name='To Address Line 1')),
                ('to_address_line_2', models.CharField(max_length=20, verbose_name='To Address Line 2')),
                ('to_address_line_3', models.CharField(max_length=20, verbose_name='To Address Line 3')),
                ('to_contact_no', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='To Contact No')),
                ('deliver_to', models.CharField(max_length=50, verbose_name='Deliver To')),
                ('deliver_to_address_line_1', models.CharField(max_length=20, verbose_name='Deliver To Address Line 1')),
                ('deliver_to_address_line_2', models.CharField(max_length=20, verbose_name='Deliver To Address Line 2')),
                ('deliver_to_address_line_3', models.CharField(max_length=20, verbose_name='Deliver To Address Line 3')),
                ('deliver_to_contact_no', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Deliver To Contact No')),
                ('customer_reference', models.CharField(max_length=50, verbose_name='Customer Reference')),
                ('responsible', models.CharField(max_length=50, verbose_name='Responsible')),
            ],
        ),
        migrations.CreateModel(
            name='Shutter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Shutter Name')),
            ],
        ),
        migrations.CreateModel(
            name='Uchannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Uchannel Name')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50, null=True)),
                ('h', models.FloatField(verbose_name='item height')),
                ('w', models.FloatField(verbose_name='item weight')),
                ('size', models.FloatField(verbose_name='item size')),
                ('location', models.CharField(max_length=25, verbose_name='Location')),
                ('shutter', models.CharField(max_length=50, null=True)),
                ('glass', models.CharField(max_length=50, null=True)),
                ('unitprice', models.FloatField(verbose_name='Total')),
                ('qty', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Qty')),
                ('value', models.FloatField(verbose_name='Value')),
                ('labour', models.FloatField(verbose_name='Labour')),
                ('transport_charge', models.FloatField(verbose_name='Transport Charge')),
                ('pl', models.CharField(max_length=50, null=True)),
                ('hl', models.CharField(max_length=50, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispaly', to='app.product')),
                ('qoutation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.quotation')),
            ],
        ),
    ]
