# Generated by Django 4.0.1 on 2022-04-13 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, verbose_name='Item Name')),
                ('rate', models.FloatField(verbose_name='Rate')),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Clip Name')),
            ],
        ),
        migrations.CreateModel(
            name='Coat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Coating Name')),
                ('rate', models.FloatField(verbose_name='Rate')),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Frame Name')),
            ],
        ),
        migrations.CreateModel(
            name='Glass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Glass Name')),
            ],
        ),
        migrations.CreateModel(
            name='Ilpatti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='I/l Patti Name')),
            ],
        ),
        migrations.CreateModel(
            name='Length',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Length')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Mnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Mosquito Net Name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Product Code')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('total_qty', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Total Qty')),
                ('totalvalue', models.FloatField(verbose_name='Total Value')),
            ],
        ),
        migrations.CreateModel(
            name='Shutter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Shutter Name')),
            ],
        ),
        migrations.CreateModel(
            name='Uchannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Uchannel Name')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50, null=True)),
                ('h', models.FloatField(verbose_name='item height')),
                ('w', models.FloatField(verbose_name='item weight')),
                ('size', models.FloatField(verbose_name='item size')),
                ('location', models.CharField(max_length=25, verbose_name='Location')),
                ('shutter', models.CharField(max_length=50, null=True)),
                ('glass', models.CharField(max_length=50, null=True)),
                ('unitprice', models.FloatField(verbose_name='Total')),
                ('qty', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Qty')),
                ('value', models.FloatField(verbose_name='Value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispaly', to='app.product')),
                ('qoutation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.quotation')),
            ],
        ),
    ]
