# Generated by Django 4.0.1 on 2022-04-23 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finalquotation',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('total_qty', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Total Qty')),
                ('totalvalue', models.FloatField(verbose_name='Basic Value')),
                ('totalsize', models.FloatField(verbose_name='Total Size')),
                ('totallabour', models.FloatField(verbose_name='Total labour')),
                ('total_transport_charge', models.FloatField(verbose_name='Total Transport Charge')),
                ('finalvalue', models.FloatField(verbose_name='Total Value')),
                ('gst', models.FloatField(verbose_name='GST')),
                ('grand_total', models.FloatField(verbose_name='Grand Total')),
            ],
        ),
        migrations.CreateModel(
            name='FinalquotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50, null=True)),
                ('h', models.FloatField(verbose_name='item height')),
                ('w', models.FloatField(verbose_name='item weight')),
                ('size', models.FloatField(verbose_name='item size')),
                ('location', models.CharField(max_length=25, verbose_name='Location')),
                ('shutter', models.CharField(max_length=50, null=True)),
                ('glass', models.CharField(max_length=50, null=True)),
                ('unitprice', models.FloatField(verbose_name='Total')),
                ('qty', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Qty')),
                ('value', models.FloatField(verbose_name='Value')),
                ('labour', models.FloatField(verbose_name='Labour')),
                ('transport_charge', models.FloatField(verbose_name='Transport Charge')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispaly', to='app.product')),
                ('qoutation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.finalquotation')),
            ],
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='qoutation',
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
        migrations.DeleteModel(
            name='QuotationItem',
        ),
    ]
