# Generated by Django 4.0.1 on 2022-02-26 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Clip Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='frame_bar',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='frame_height',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='frame_type',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='frame_width',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='glass_rate',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='glass_type',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='il_rate',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='il_type',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='net_rate',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='net_type',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='qid',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='uch_rate',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='uch_type',
        ),
        migrations.AddField(
            model_name='quotation',
            name='_id',
            field=models.IntegerField(auto_created=True, default=1, verbose_name='Quotation Id'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_width', models.FloatField(verbose_name='Frame Width')),
                ('frame_height', models.FloatField(verbose_name='Frame Height')),
                ('frame_rate', models.FloatField(verbose_name='Frame Rate')),
                ('glass_rate', models.FloatField(verbose_name='Glass Rate')),
                ('il_rate', models.FloatField(verbose_name='I/L patti Rate')),
                ('net_rate', models.FloatField(verbose_name='Net Rate')),
                ('uch_rate', models.FloatField(verbose_name='U-channel Rate')),
                ('coat_rate', models.FloatField(verbose_name='Coating Rate')),
                ('qty', models.PositiveIntegerField(verbose_name='Quantity')),
                ('coat_type', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.PROTECT, to='app.coat', verbose_name='Coating Type')),
                ('frame_bar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.length', verbose_name='Frame Unit size')),
                ('frame_type', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.PROTECT, to='app.frame')),
                ('glass_type', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.PROTECT, to='app.glass', verbose_name='Glass Type')),
                ('il_type', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.PROTECT, to='app.ilpatti', verbose_name='I/L patti Type')),
                ('net_type', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.PROTECT, to='app.mnet', verbose_name='Net Type')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.product')),
                ('uch_type', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.PROTECT, to='app.uchannel', verbose_name='U-channel Type')),
            ],
        ),
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, verbose_name='Item Name')),
                ('rate', models.FloatField(verbose_name='Rate')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.product', verbose_name='Product Name')),
            ],
        ),
        migrations.AddField(
            model_name='quotation',
            name='items',
            field=models.ManyToManyField(to='app.Products', verbose_name='items'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='addon_type',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.PROTECT, to='app.addon', verbose_name='Addon Type'),
        ),
    ]
