# Generated by Django 4.0.1 on 2022-02-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_clip_remove_quotation_frame_bar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='nos',
            field=models.CharField(default=1, max_length=50, verbose_name='Item Name'),
            preserve_default=False,
        ),
    ]
