# Generated by Django 4.0.1 on 2022-04-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_finalquotation_finalquotationitem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Finalquotation',
            new_name='Quotation',
        ),
        migrations.RenameModel(
            old_name='FinalquotationItem',
            new_name='QuotationItem',
        ),
    ]
