# Generated by Django 4.0.1 on 2022-04-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_finalquotation_quotation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='grand_total',
            new_name='summery',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='totalvalue',
            field=models.FloatField(verbose_name='Total Value'),
        ),
    ]
