# Generated by Django 4.0.1 on 2022-02-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_quotation_addon_type_remove_quotation_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default=1, max_length=10, verbose_name='Product Code'),
            preserve_default=False,
        ),
    ]
