# Generated by Django 4.0.1 on 2022-04-30 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_quotationitem_hl'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quotation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
